# Generated by Django 3.2.5 on 2021-07-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeroBox', '0004_heromodels_buttontxt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heromodels',
            old_name='Alt',
            new_name='alt',
        ),
    ]
