# Generated by Django 3.2.5 on 2021-07-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimodels',
            name='Alt',
            field=models.CharField(default='some string', max_length=50),
        ),
    ]
