# Generated by Django 3.2.5 on 2021-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonial', '0003_testimodels_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimodels',
            old_name='Alt',
            new_name='alt',
        ),
    ]
