# Generated by Django 3.2.5 on 2021-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testimonial', '0004_rename_alt_testimodels_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimodels',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
