# Generated by Django 3.2.5 on 2021-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_alter_servicemodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodels',
            name='image',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
