# Generated by Django 3.2.5 on 2021-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_remove_servicemodels_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodels',
            old_name='Alt',
            new_name='alt',
        ),
    ]
