# Generated by Django 3.2.5 on 2021-07-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutmodels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Body', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to=None)),
                ('Alt', models.CharField(default='some string', max_length=50)),
            ],
        ),
    ]
