# Generated by Django 3.2.5 on 2021-07-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0002_rename_alt_aboutmodels_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodels',
            old_name='Body',
            new_name='body',
        ),
    ]
