# Generated by Django 3.2.5 on 2021-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0003_rename_body_aboutmodels_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodels',
            name='title1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
