# Generated by Django 3.2.5 on 2021-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0002_featuresmodels_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresmodels',
            name='image',
            field=models.ImageField(default='null', upload_to=None),
        ),
    ]
