# Generated by Django 3.2.5 on 2021-07-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Features', '0003_alter_featuresmodels_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuresmodels',
            old_name='Alt',
            new_name='alt',
        ),
    ]
